create table shop_section_keywords (
  id       bigint primary key generated always as identity,
  section  text not null,
  keyword  text not null,
  unique (section, keyword)
);

insert into shop_section_keywords (section, keyword) values
('produce', 'apple'),
('produce', 'apples'),
('produce', 'avocado'),
('produce', 'banana'),
('produce', 'basil'),
('produce', 'bean'),
('produce', 'beans'),
('produce', 'beet'),
('produce', 'bell pepper'),
('produce', 'broccoli'),
('produce', 'cabbage'),
('produce', 'carrot'),
('produce', 'carrots'),
('produce', 'cauliflower'),
('produce', 'celery'),
('produce', 'cilantro'),
('produce', 'corn'),
('produce', 'cucumber'),
('produce', 'dill'),
('produce', 'eggplant'),
('produce', 'fennel'),
('produce', 'garlic'),
('produce', 'ginger'),
('produce', 'grape'),
('produce', 'grapes'),
('produce', 'green bean'),
('produce', 'herb'),
('produce', 'jalapeño'),
('produce', 'kale'),
('produce', 'leek'),
('produce', 'lemon'),
('produce', 'lemons'),
('produce', 'lettuce'),
('produce', 'lime'),
('produce', 'limes'),
('produce', 'mango'),
('produce', 'mint'),
('produce', 'mushroom'),
('produce', 'mushrooms'),
('produce', 'onion'),
('produce', 'onions'),
('produce', 'orange'),
('produce', 'parsley'),
('produce', 'peach'),
('produce', 'pear'),
('produce', 'peas'),
('produce', 'pepper'),
('produce', 'peppers'),
('produce', 'potato'),
('produce', 'potatoes'),
('produce', 'radish'),
('produce', 'rosemary'),
('produce', 'sage'),
('produce', 'scallion'),
('produce', 'shallot'),
('produce', 'spinach'),
('produce', 'squash'),
('produce', 'strawberry'),
('produce', 'sweet potato'),
('produce', 'thyme'),
('produce', 'tomato'),
('produce', 'tomatoes'),
('produce', 'zucchini'),
('meat', 'anchovy'),
('meat', 'bacon'),
('meat', 'beef'),
('meat', 'chicken'),
('meat', 'chorizo'),
('meat', 'clam'),
('meat', 'cod'),
('meat', 'crab'),
('meat', 'duck'),
('meat', 'fish'),
('meat', 'ground beef'),
('meat', 'ground pork'),
('meat', 'ground turkey'),
('meat', 'ham'),
('meat', 'lamb'),
('meat', 'lobster'),
('meat', 'pancetta'),
('meat', 'pork'),
('meat', 'prosciutto'),
('meat', 'salmon'),
('meat', 'sausage'),
('meat', 'scallop'),
('meat', 'shrimp'),
('meat', 'steak'),
('meat', 'tilapia'),
('meat', 'tuna'),
('meat', 'turkey'),
('dairy', 'butter'),
('dairy', 'cheddar'),
('dairy', 'cheese'),
('dairy', 'cottage cheese'),
('dairy', 'cream'),
('dairy', 'cream cheese'),
('dairy', 'egg'),
('dairy', 'eggs'),
('dairy', 'feta'),
('dairy', 'goat cheese'),
('dairy', 'gruyere'),
('dairy', 'half and half'),
('dairy', 'heavy cream'),
('dairy', 'mascarpone'),
('dairy', 'milk'),
('dairy', 'mozzarella'),
('dairy', 'parmesan'),
('dairy', 'pecorino'),
('dairy', 'ricotta'),
('dairy', 'sour cream'),
('dairy', 'whipped cream'),
('dairy', 'yogurt'),
('pantry', 'baking powder'),
('pantry', 'baking soda'),
('pantry', 'bean'),
('pantry', 'beans'),
('pantry', 'broth'),
('pantry', 'brown sugar'),
('pantry', 'buckwheat'),
('pantry', 'canned'),
('pantry', 'cannellini'),
('pantry', 'chickpea'),
('pantry', 'chickpeas'),
('pantry', 'chocolate'),
('pantry', 'cocoa'),
('pantry', 'coconut milk'),
('pantry', 'cornstarch'),
('pantry', 'couscous'),
('pantry', 'ditalini'),
('pantry', 'dried'),
('pantry', 'extract'),
('pantry', 'fish sauce'),
('pantry', 'flour'),
('pantry', 'honey'),
('pantry', 'hot sauce'),
('pantry', 'jam'),
('pantry', 'ketchup'),
('pantry', 'lentil'),
('pantry', 'lentils'),
('pantry', 'maple syrup'),
('pantry', 'mayonnaise'),
('pantry', 'mirin'),
('pantry', 'miso'),
('pantry', 'mustard'),
('pantry', 'noodle'),
('pantry', 'noodles'),
('pantry', 'nutritional yeast'),
('pantry', 'oat'),
('pantry', 'oats'),
('pantry', 'oil'),
('pantry', 'olive oil'),
('pantry', 'oregano'),
('pantry', 'panko'),
('pantry', 'paprika'),
('pantry', 'pasta'),
('pantry', 'pepper flakes'),
('pantry', 'quinoa'),
('pantry', 'rice'),
('pantry', 'rice vinegar'),
('pantry', 'salt'),
('pantry', 'sesame oil'),
('pantry', 'soy sauce'),
('pantry', 'spice'),
('pantry', 'stock'),
('pantry', 'sugar'),
('pantry', 'tahini'),
('pantry', 'tomato paste'),
('pantry', 'vanilla'),
('pantry', 'vinegar'),
('pantry', 'worcestershire'),
('bread', 'baguette'),
('bread', 'bread'),
('bread', 'brioche'),
('bread', 'bun'),
('bread', 'buns'),
('bread', 'ciabatta'),
('bread', 'crouton'),
('bread', 'english muffin'),
('bread', 'flatbread'),
('bread', 'naan'),
('bread', 'pita'),
('bread', 'roll'),
('bread', 'rolls'),
('bread', 'sourdough'),
('bread', 'tortilla'),
('bread', 'tortillas'),
('bread', 'wrap'),
('frozen', 'frozen'),
('frozen', 'ice cream'),
('frozen', 'popsicle');
